### ISSUE TITLE
Does not compile with current Arduino Tensoflow Lite library.

### ISSUE THREAD

**Issue by SteffCGN** [ushan-fernando/Fitnetic#1]
Hi,

which library version did you use? I can't seem to find a version that works with the current souce code.

Cheers,

Stefan

**Comment by ushan-fernando** [comment]
Hi Stefan,

Looking back at my files, the Arduino_TensorFlowLite library used was version 2.4.0-ALPHA. I'm not quite sure if this version is still downloadable, as it appears to be unavailable in the Arduino Library Manager. 

Maybe the instructions in this forum discussion might prove useful to solve this: [https://forum.arduino.cc/t/why-i-cant-find-the-arduino-tensorflowlite-library-in-library-management/1044070](url).

Best wishes,

Ushan

**Comment by SteffCGN** [comment]
That was a very fast answer, thank you!
